### DISCUSSION TITLE
is there a way to add the cluster name as context for slack notication?

### DISCUSSION THREAD

**Discussion by renperez** [argoproj-labs/argocd-notifications#169] [Q&A]
I want to add the cluster name on my slack notification. is there a way to add that? I was able to add the context for argocd url but was wondering if i can add the cluster name as well, since we are using argo for multiple cluster.

**Comment by alexmt** [comment]
Hello @renperez ,

Yes, context might contain any key, not just `argocdUrl`. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  config.yaml: |
    context:
      argocdUrl: <argocd-url>
      clusterName: <clusterName>
```

The value might be used as `{{.context.clusterName}}`

**Comment by renperez** [comment]
thanks @alexmt. I tried adding it with this value {{.context.clusterName}} and the slack notification stopped working. is this the correct value?

**Comment by alexmt** [comment]
The `{{.context.clusterName}} ` was added to the template, right? Can you please share the template?

Also feel free to join our slack: https://argoproj.github.io/community/join-slack . It will be easier to troubleshoot

**Comment by keanlee** [comment]
ClusterName: <no value>. seem the {{.context.clusterName}} is not work?

**Comment by keanlee** [comment]
> ClusterName: . seem the {{.context.clusterName}} is not work?

https://github.com/argoproj-labs/argocd-notifications/issues/67#issuecomment-616557686

**Comment by alexmt** [comment]
Hello @keanlee, @renperez  ,

I've implemented a CLI [commands](https://argoproj-labs.github.io/argocd-notifications/troubleshooting/) that helps troubleshooting configuration issues. 

The CLI is not released yet but available in `argoprojlabs/argocd-notifications:latest` image . You might use it as follows:

* save `argocd-notification-cm` into local file.

* use [template notify](https://argoproj-labs.github.io/argocd-notifications/troubleshooting/#tools-template-notify) command to generate notification in debug mode

```
docker run --rm -it  -w /src -v $(pwd):/src  argoprojlabs/argocd-notifications:latest \
  /app/argocd-notifications tools template notify app-sync-succeeded foobar.yaml --config-map config-map.yaml --secret :empty
```
Give it a try please.

**Comment by pp185214** [comment]
Could I ask how to set {{.context.argocdUrl}} now? I can see that setting which is like

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  config.yaml: |
    context:
      argocdUrl: <argocd-url>
```

stopped working. I am on version 1.8.6 thanks a lot for help.

**Reply by pp185214** [reply]
I have tried 


```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
    context: |
      argocdUrl: <argocd-url>
```

But it's still same. Thing is that I can see in Slack messages `https://localhost:4000` insead of url which is set in argocd-cm
