### DISCUSSION TITLE
Slack template for app-created and app-deleted

### DISCUSSION THREAD

**Discussion by ashwin316** [argoproj-labs/argocd-notifications#279] [Q&A] [answered]
Hi everyone

I am trying to send notification if an app is created/deleted, and have configured everything using helm charts. Using the argocd-notifications v1.1.0

Below are my trigger conditions:

```
triggers:
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-succeeded: |
    - description: Application is synced. Triggered once per sync.
      oncePer: app.status.operationState.operation.sync.revision
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
  trigger.on-created: |
    - description: Application is created.
      oncePer: app.metadata.name
      when: true
  trigger.on-deleted: |
    - description: Application is deleted.
      oncePer: app.metadata.name
      when: app.metadata.deletionTimestamp != nil
```

Below is my templates section (just adding the app-created template for less content):

```
templates:
  template.app-created: |
    message: |
      Application {{.app.metadata.name}} has been created.
    slack:
      attachments: "[{"title": "Application {{.app.metadata.name}} has been created."}] "
```

The JSON for template is valid, and once applied it shows up properly in the configmap also.

However I get the following error whenever a new app is created:

`time="2021-05-04T11:49:46Z" level=error msg="Failed to notify recipient {slack argo-notifs} defined in app argo/new-app: no_text" app=argo/new-app`

Can anyone help me here please??

**Comment by ashwin316** [comment, marked as answer]
I found the issue and solved it. I had missed the `send` key in the triggers section. Works with the following:

```
trigger.on-created: |
  - description: Application is created.
    oncePer: app.metadata.name
    send:
    - app-created
    when: true
trigger.on-deleted: |
  - description: Application is deleted.
    oncePer: app.metadata.name
    send:
    - app-deleted
    when: app.metadata.deletionTimestamp != nil
```
