### DISCUSSION TITLE
Spamming notification

### DISCUSSION THREAD

**Discussion by VA-PLE** [argoproj-labs/argocd-notifications#285] [Q&A]
Hi, I have a repository with several helm charts, and when I make a committee in one of them, I get a notification about app-deployed for all my apps, although there have been no changes made for them. How can I solve this problem?
I need the notification to come for only app for which the changes were made.

my current trigger:
```
trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState.syncResult.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
