### DISCUSSION TITLE
Single app update in multiple app repository triggers sync event on all apps

### DISCUSSION THREAD

**Discussion by gdznela** [argoproj-labs/argocd-notifications#346] [Q&A]
I have multiple apps (helm) deployed via app of apps pattern, all residing in folders in same git repository:
`app1, app2, app3... appN`. 
I have configured trigger for on-deployed event (from example in helm chart):

```
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
and default subsciption:

```
  subscriptions:
    - recipients:
      - slack:release
      triggers:
      - on-deployed
```

Now if I change file(s) in `app1` folder, trigger is firing on all other apps as well: `app2, app3 ... appN`, spamming slack with unneeded messages about apps that are not affected by change and are not actually deployed.
I want to be notified only about apps that are actually updated/deployed. Is there any workaround to achieve this?
