### DISCUSSION TITLE
How to enable teams notification ?

### DISCUSSION THREAD

**Discussion by timam** [argoproj-labs/argocd-notifications#374] [Q&A]
I have a helm chart, and I deploy that chart into EKS with ArgoCD. Now my goal is to get notification on Teams channel after sync. 
As described on https://argocd-notifications.readthedocs.io/en/stable/ ; I have installed Argo CD Notifications and riggers and Templates from the catalog. 
Since my plan is to make teams notification workable, I jumped to https://argocd-notifications.readthedocs.io/en/stable/services/teams/
and followed step 1 to 6. Then comes the following part which confuses me. 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: TestChan
``` 
If I try to run kubectl apply it gives me validation warning, after skipping warning, it gives me following error 

```
error: error when retrieving current configuration of:
Resource: "argoproj.io/v1alpha1, Resource=applications", GroupVersionKind: "argoproj.io/v1alpha1, Kind=Application"
Name: "", Namespace: "argocd"
from server for: "teams.yaml": resource name may not be empty
```
