### DISCUSSION TITLE
Didn't work ArgoCD notifications

### DISCUSSION THREAD

**Discussion by ytooyama** [argoproj-labs/argocd-notifications#400] [Q&A]
I have installed the Argo CD.
The Argo CD is working fine.

But The notification function of Argo CD is not working well.

I set it up according to Getting Started, but no notifications are sent to my email address.

https://github.com/argoproj-labs/argocd-notifications/blob/master/docs/index.md

Case:

```
kubectl apply -n argocd -f - << EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: <Set the My Gmail Address>
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
EOF
```

I also tried Argo CD notification 1.2.1 but didn't receive any emails as well.

Where can I find the operating requirements for argocd-notifications?

My Environment:

- Kubernetes v1.22.9 (microk8s)
- Kubernetes Helm v3.5.0
- Argo CD v2.3.3+07ac038
- argocd-notifications 1.2.1

Thanks.
