### DISCUSSION TITLE
how to Integrate shell script in webhook?

### DISCUSSION THREAD

**Discussion by hillbun** [argoproj-labs/argocd-notifications#403] [General]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: <config-map-name>
data:
  service.webhook.form: |
    url: https://form.example.com
    headers:
    - name: Content-Type
      value: application/x-www-form-urlencoded

  template.form-data: |
    webhook:
      form:
        method: POST
        body: key1=value1&key2=value2
```

I write script to get a token

URL="https://xxxx.xxx.xxx/cgi-bin/gettoken"
token=$(curl -s -G $URL)

How to pass token value to value2 of configmap above?
