### DISCUSSION TITLE
Failed to notify recipient {webhook dingtalk } defined in resource xxx: notification service 'webhook dingtalk' is not supported

### DISCUSSION THREAD

**Discussion by lazychanger** [argoproj-labs/argocd-notifications#416] [Q&A] [answered]
| title | tag |
| - | - |
|Argo CD|v2.4.3+471685f|
|Build Date|2022-06-27T21:02:55Z|
|Go Version|go1.18.3|
|Go Compiler|gc|
|Platform|linux/amd64|
|jsonnet|v0.18.0|
|kustomize|v4.4.1 2021-11-11T23:36:27Z|
|Helm|v3.8.1+g5cb9af4|
|kubectl|v0.23.1|

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.9.11
  name: argocd-notifications-controller-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "http://argocd.example.com"
  service.webhook.dingtalk: |
    url: https://oapi.dingtalk.com/robot/send?access_token=$dingtalk-accesstoken
    headers:
      - name: Content-Type
        value: application/js
  subscriptions: |
    - recipients:
      - webhook:dingtalk
      triggers:
      - on-sync-running
      - on-sync-failed
      - on-sync-status-unknown
      - on-deployed
      - on-sync-succeeded
      - on-health-degraded
  template.app-sync-change: |
    webhook:
      dingtalk:
        method: POST
        body: |
          {
              "msgtype": "markdown",
              "markdown": {
                  "title":"ArgoCD sync status",
                  "text": "### ArgoCD sync status\n> - appname: {{.app.metadata.name}}\n> - app sync status: {{ .app.status.operationState.phase}}\n> - date:{{.app.status.operationState.startedAt}}\n> - URL: [jump ArgoCD]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true) \n"
              }
          }
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-running: |
    - description: Application is being synced
      send:
      - app-sync-running
      when: app.status.operationState.phase in ['Running']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
```

```txt
time="2022-07-05T03:18:00Z" level=info msg="Start processing" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-sync-running result: [{[0].xGlbhcF_taGYrI3UsrQsINn2hl0  [app-sync-running] false}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-sync-failed result: [{[0].H9WjsqG1dKYm6njOZ7yUQYOA1Wk  [app-sync-failed] false}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-sync-status-unknown result: [{[0].6SzWb05EK-0v90hwjyytTbN7S6A  [app-sync-status-unknown] false}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-deployed result: [{[0].y7b5sbwa2Q329JYH755peeq-fBs 936f8edfabf78c47a015e0c047af5c28d70f7aa3 [app-deployed] true}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Notification about condition 'on-deployed.[0].y7b5sbwa2Q329JYH755peeq-fBs' already sent to '{webhook dingtalk}'" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0  [app-sync-succeeded] true}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{webhook dingtalk}'" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=error msg="Failed to notify recipient {webhook dingtalk} defined in resource argocd/v3-api: notification service 'webhook' is not supported" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Trigger on-health-degraded result: [{[0].zoG5zUjYGjimkwCGgIQGjx1hO5s  [app-health-degraded] false}]" resource=argocd/v3-api
time="2022-07-05T03:18:00Z" level=info msg="Processing completed" resource=argocd/v3-api
```
