### DISCUSSION TITLE
Unable to get email notifications working: notification service 'email' is not supported"

### DISCUSSION THREAD

**Discussion by trudesea** [argoproj-labs/argocd-notifications#419] [General]
Hi,

I just started using argocd a few days ago.   I'm having an issue getting emaill to work.   I have an smtp that does not require authorization.  My configmap is as follows

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycosmtp
data:
  service.email.myco: |
    host: smtp.myco.com
    port: 25
    from: me@myco.com

```
```
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argocd-notifications-cm
data:
  subscriptions: |
    - recipients:
      - email:me@myco.com
      triggers:
      - on-sync-succeeded
      - on-sync-status-unknown
      - on-sync-failed
      - on-health-degraded
      - on-deployed
      - on-deleted
      - on-created
      - on-sync-running
```

I am getting this error in the gke logs: 
```
textPayload: "time="2022-08-04T18:07:16Z" level=error msg="Failed to notify recipient {email me@myco.com} defined in resource argocd/cd-jenkins: notification service 'email' is not supported" resource=argocd/cd-jenkins"
timestamp: "2022-08-04T18:07:16.445265636Z"
```

What am I missing here?

Thanks
