### DISCUSSION TITLE
ArgoCD Alert not Send Notifcation On Slack

### DISCUSSION THREAD

**Discussion by Zeeshan50522** [argoproj-labs/argocd-notifications#425] [General]
I have followed the document for [argocd alert on slack ](https://argocd-notifications.readthedocs.io/en/stable/services/slack/) 
argocd-notifications-controller showing all the Triggers in pod logs but still i'm not getting notification in slack

Controller log
```
level=info msg="Start processing" app=argocd/service
level=info msg="Trigger on-health-degraded result: []" app=argocd/service
level=info msg="Trigger on-sync-failed result: []" app=argocd/service
level=info msg="Trigger on-sync-status-unknown result: []" app=argocd/service
level=info msg="Trigger on-sync-succeeded result: []" app=argocd/service
level=info msg="Trigger on-deployed result: []" app=argocd/service
level=info msg="Processing completed" app=argocd/service
```

ConfigMap File
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  defaultTriggers: |
    - on-deployed
    - on-health-degraded
    - on-sync-failed
    - on-sync-running
    - on-sync-status-unknown
    - on-sync-succeeded
```
Secret 

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  #namespace: argocd
stringData:
  slack-token: <My-Slack-Secret>
```

I am using latest versions of argocd and notification controller
