### DISCUSSION TITLE
Discord webhook setup method should be described in detail

### DISCUSSION THREAD

**Discussion by kumo-rn5s** [argoproj-labs/argocd-notifications#429] [Show and tell]
I tried to send a message to discord through normal webhook, and i found this.

If trigger definition is missing in `argocd-notifications-cm`, the message will not be sent and there will be no error in the controller's log, even if I installed triggers from Catalog, and set up annotation according to the documentation, 
like `on-deployed` in `notifications.argoproj.io/subscribe.on-deployed.<webhook name>` 

What I did was to define some triggers and use that trigger in an annotation.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.discord_webhook: |
    url: https://discord.com/api/webhooks...
    headers:
    - name: Content-Type
      value: application/json
  trigger.on-deployed: |
    - when: ...
  template.app-deployed: |
    webhook:
      discord_webhook:
        method: POST
        body: |
          {...}
```

`kubectl patch app <application name> -n argocd -p '{"metadata": {"annotations": {"notifications.argoproj.io/subscribe.on-deployed.discord_webhook":""}}}' --type merge
`

Discord webhook setup method should be described in detail in the `v:latest` documentation.
