### ISSUE TITLE
Handling of secret

### ISSUE THREAD

**Issue by yuzujoe** [argoproj-labs/argocd-notifications#107]
Why are we dealing with secrets in the form of `notifiers.yaml`?

I find it very difficult to use as it makes it incompatible with other secrets.
Also, because of using stringData, the only way to save values is to store them in plain text, which is a risk from a security perspective.

If there is a way to handle resources such as `ExternalSecrets` and `SaledSecrets` flexibly, I would like to see some documentation.

**Comment by booleanbetrayal** [comment]
This can be done pretty easily with the Helm deployment for argocd-notifications. There's a value (`.secret.create`) that can be toggled to `false`. At that point, just ensure your `ExternalSecret` is named identical to the expected `Secret` (`argocd-notifications-secret`) and that it provides the correct key:

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd
    argocd.argoproj.io/instance: argocd
  name: argocd-notifications-secret
  namespace: argocd
spec:
  backendType: secretsManager
  data:
  - key: your-externally-backed-encrypted-store-notifiers-yaml
    name: notifiers.yaml
  template:
    metadata:
      annotations:
        app.kubernetes.io/part-of: argocd
        managed-by: argocd.argoproj.io
```
