### ISSUE TITLE
ArgoCD notifications is ignoring repo server for custom template

### ISSUE THREAD

**Issue by thiagonache** [argoproj-labs/argocd-notifications#110]
Hi guys,

I'm having issues implementing custom templates with argocd. Everything works with builtin templates, but when I create my custom template, it seems to be ignoring parameter --repo-server.
Container startup:
```
Containers:
  application-controller:
    Container ID:  docker://f25c79322a92be3cb0d40c1ea874a58b3c27041a52bb15020703938cf35344b0
    Image:         argoproj/argocd:v1.6.1
    Image ID:      docker-pullable://argoproj/argocd@sha256:0a8fa1fee472568c2ec49dc1a71d3af56613b6b62353560a3682abc24492daee
    Port:          8082/TCP
    Host Port:     0/TCP
    Command:
      argocd-application-controller
      --status-processors
      20
      --operation-processors
      10
      --repo-server
      dev-argocd-repo-server:8081
      --loglevel
      info
      --redis
      dev-argocd-redis:6379
```

Configuration:
```
apiVersion: v1
data:
  config.yaml: |
    context:
      argocdUrl: "https://argocd.mydomain.com"
    subscriptions:
      []
    templates:
      - body: 'Author: {{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}'
        name: default-template
        title: Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
    triggers:
      - enabled: true
        name: on-sync-succeeded
        template: default-template
      - condition: time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes()
          >= 5
        enabled: true
        name: app-operation-stuck
        template: default-template
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: dev-argocd-notifications
    meta.helm.sh/release-namespace: dev-argocd
  creationTimestamp: "2020-07-20T15:25:56Z"
  labels:
    app.kubernetes.io/instance: dev-argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: 0.7.0
    helm.sh/chart: argocd-notifications-1.0.7
  name: argocd-notifications-cm
  namespace: dev-argocd
```
Error to render template:
```
time="2020-07-20T16:23:41Z" level=error msg="Failed to process: template: default-template:1:11: executing \"default-template\" at <call .repo.GetCommitMetadata .app.status.sync.revision>: error calling call: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup argocd-repo-server on 10.192.0.10:53: no such host\"" app=dev-argocd/my-service
```

I apologise in advance if I'm missing something.
