### ISSUE TITLE
Bug: Resending notification when one trigger has failed

### ISSUE THREAD

**Issue by olegsu** [argoproj-labs/argocd-notifications#115]
I have created the following `argocd-notifications-cm` with subscriptions:
```yaml
      subscriptions:
        - recipients:
          - slack:some-channel
          trigger: custom-trigger
```

Then I've added another recipient: `- email:myemail@gmail.com`, the notifier YAML is not updated, yet.
As a result, the controller keeps sending the slack notification because the SMTP was not configured yet.
I think it is because of the missing annotation that the controller adds to the application.
A fix can be either to add the annotation, logging the fact that not all the notifications have been sent. Or, to create annotation per recipient.
