### ISSUE TITLE
Bug: resend notification when the trigger name is too long

### ISSUE THREAD

**Issue by olegsu** [argoproj-labs/argocd-notifications#117]
The annotation will be rejected by kuberntes API server when the regex `([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]` is not matched. 
I suggest adding validations on the trigger names to have some length and valid for the API server when the configmap is patched.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj-labs/argocd-notifications/pull/116

**Comment by fvillain** [comment]
Having the same problem here. Would be interested in a patch for that. 
Could we save notification status in a yaml structure instead ?

```yaml
metadata:
  annotations:
     on-sync-succeeded.argocd-notifications.argoproj.io: 
        slack.{slackChannelOne}: {timestamp}
        slack.{slackChannelTwo}: {timestamp2}
```
