### ISSUE TITLE
(feat): ArgoCD Notifications for Created, Deleted status

### ISSUE THREAD

**Issue by lukasmrtvy** [argoproj-labs/argocd-notifications#125]
Would be great to have support for `Created`, `Deleted` status in argo-notifications, it can be used for (de)register webhook.

Thanks

**Comment by alexmt** [comment]
This should be supported using `oncePer` trigger field:

```yaml
  trigger.created: |
    - description: Application is created.
      oncePer: app.metadata.name
      when: true
  trigger.created: |
    - description: Application is deleted.
      oncePer: app.metadata.name
      when: app.metadata.deletionTimestamp != nil
```

I think it worth to contribute it to catalog: https://github.com/argoproj-labs/argocd-notifications/tree/master/catalog
