### ISSUE TITLE
Argo notifications fails to send notification with "invalid character '{' after array element". This is caused by Warnings on ArgoCD

### ISSUE THREAD

**Issue by ArjonBu** [argoproj-labs/argocd-notifications#126]
I am having trouble trying to make Argo notifications work. I am using version 0.7.0

I get the following error:

`time="2020-11-19T08:57:06Z" level=error msg="Failed to notify recipient slack:test-channel defined in app argocd/staging: failed to unmarshal attachments '[{\n\t\"title\": \"staging\",\n\t\"title_link\": \"https://localhost:4000/applications/staging\",\n\t\"color\": \"#18be52\",\n\t\"fields\": [\n\t{\n\t\t\"title\": \"Sync Status\",\n\t\t\"value\": \"Synced\",\n\t\t\"short\": true\n\t},\n\t{\n\t\t\"title\": \"Repository\",\n\t\t\"value\": \"https://git.domain.com/repo/k8s.git\",\n\t\t\"short\": true\n\t}\n\t\n\t,\n\t{\n\t\t\"title\": \"SharedResourceWarning\",\n\t\t\"value\": \"CustomResourceDefinition/apmservers.apm.k8s.elastic.co is part of a different application: elastic-operator\",\n\t\t\"short\": true\n\t}\n\t\n\t\n\t{\n\t\t\"title\": \"SharedResourceWarning\",\n\t\t\"value\": \"CustomResourceDefinition/beats.beat.k8s.elastic.co is part of a different application: elastic-operator\",\n\t\t\"short\": true\n\t}\n\t\n\t\n\t{\n\t\t\"title\": \"SharedResourceWarning\",\n\t\t\"value\": \"CustomResourceDefinition/elasticsearches.elasticsearch.k8s.elastic.co is part of a different application: elastic-operator\",\n\t\t\"short\": true\n\t}\n\t\n\t\n\t{\n\t\t\"title\": \"SharedResourceWarning\",\n\t\t\"value\": \"CustomResourceDefinition/enterprisesearches.enterprisesearch.k8s.elastic.co is part of a different application: elastic-operator\",\n\t\t\"short\": true\n\t}\n\t\n\t\n\t{\n\t\t\"title\": \"SharedResourceWarning\",\n\t\t\"value\": \"CustomResourceDefinition/kibanas.kibana.k8s.elastic.co is part of a different application: elastic-operator\",\n\t\t\"short\": true\n\t}\n\t\n\t]\n}]' : invalid character '{' after array element" app=argocd/staging`

The error seems to be related to a template because of `invalid character '{' after array element"`

Here is my configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  config.yaml: |
    subscriptions:
      - recipients:
        - slack:test-channel
    triggers:
      - name: on-sync-succeeded
        enabled: true
      - name: on-sync-failed
        enabled: true
      - name: on-sync-status-unknown
        enabled: true
      - name: on-health-degraded
        enabled: true
      - name: on-sync-status-unknown
        enabled: true

```
