### ISSUE TITLE
Custom template notification conflicts with helm denotate expression placeholder {{ }}

### ISSUE THREAD

**Issue by mateustanaka** [argoproj-labs/argocd-notifications#127]
I'm using helm chart templates on top of the template used by argocd internally and I want to add custom notification templates on **agocd-notifications-cm** ConfiMap, like the example below:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    context:
      argocdUrl: {{ .Values.argocdUrl }}
    triggers:
      - name: on-sync-failed
        enabled: true
        template: my-custom-template
  template: |
    - name: my-custom-template
      title: Failed to sync application {{.app.metadata.name}}.
      body: |
        {{if eq .context.notificationType "slack"}}:exclamation:{{end}}  The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
        Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
        Team @my-team take a look at it.
```

We have helm placeholder expressions `{{ .Values.argocdUrl }}` and some others used by argocd-notifications like `{{.app.metadata.name}}`.

After installing argocd-notifications I get the error:

`rpc error: code = Unknown desc = "helm template . --name-template argocd-notification failed exit status 1: Error: template: argocd-notification/templates/config-map.yaml:17:46: executing "argocd-notification/templates/config-map.yaml" at <.app.metadata.name>: nil pointer evaluating interface {}.metadata Use --debug flag to render out invalid YAML`

It seems an error from the helm template, but how can I create a custom notification template with helm at the same time?
