### ISSUE TITLE
docs: how to send webhook with form-data

### ISSUE THREAD

**Issue by llienard** [argoproj-labs/argocd-notifications#134]
Hi,

I would like to send a webhook to jenkins with parameters.

The documentation does not show how to send webhook with form-data. Is this possible ?

Thanks

**Comment by romachalm** [comment]
I had this need for gitlab-ci triggers which only accept form data. Here is how I have solved it. 

Switch the content type of the service to `x-www-form-urlencoded` : 
```yaml
  service.webhook.gitlab-trigger-tests: |
    url: "https://gitlab.com/api/v4/projects/xxx/trigger/pipeline"
    headers:
      - name: Content-Type
        value: application/x-www-form-urlencoded
```

In the template, pass your data as url format (ie `name1=val1&name2=val2`). No need to escape, Go html template does it. 
For instance, here I pass the trigger token, the branch and the URL of the app ingress to be used in my gitlab-ci job. 
```yaml
  template.all-good: |
    description: Generates slack webhook payload
    webhook:
      gitlab-trigger-tests:
        method: POST
        body: "token=xxxx&ref=master&variables[URL]={{index .app.status.summary.externalURLs 0}}"
```

Hope it helps
