### ISSUE TITLE
Key config.yaml does not match to any pattern

### ISSUE THREAD

**Issue by CurryWurry** [argoproj-labs/argocd-notifications#138]
Hi all,

Do you know what this warning means in the logs? I try to configure email notifications, but nothing is being send, so I might have a config issue somewhere. We are running version 0.7.0 on Openshift 4.6, but have also tried the latest image. 

Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifier.email: |
    host: my.mail.server.com
    port: 25
    username: ""
    password: ""
    from: no-reply-foo@company.com
type: Opaque
```
ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    subscriptions:
      - recipients:
        - email: my.email@company.com
    templates:
      - name: success-template
        title: Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
        body: |
          Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
          Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    triggers:
      - name: on-sync-succeeded
        condition: app.status.sync.status == 'Succeeded'
        template: success-template
        enabled: true
```
