### ISSUE TITLE
Parsing Config.subscriptions in ConfigMap fails

### ISSUE THREAD

**Issue by gskolysz** [argoproj-labs/argocd-notifications#144]
Hi!

This seems like a cool project, and so I wanted to use it for sending notifications via webhooks.
I added argocd-notifications-secret and argocd-notifications-cm in which I wanted to use default subscriptions, so I don't need to annotate Apps/AppProjects (or have I misunderstood the feature?).

However, adding `subscriptions` to the ConfigMap results in pod failing to start, throwing:
```
➜  ~ kubectl logs argocd-notifications-controller-5497587c65-rrtd7 -n argocd
time="2021-01-05T13:52:39Z" level=info msg="serving metrics on port 9001"
time="2021-01-05T13:52:39Z" level=info msg="loading configuration 9001"
time="2021-01-05T13:52:39Z" level=info msg="config map found"
time="2021-01-05T13:52:39Z" level=info msg="secret found"
time="2021-01-05T13:52:39Z" level=fatal msg="Failed to parse new settings: error unmarshaling JSON: json: cannot unmarshal string into Go struct field Config.subscriptions of type []string"
```

When there's no `subscriptions` in the ConfigMap, the pod starts without any issues.

Full configmap contents here (it is jinja2 since I am using ansible to deploy it, but it :

``` yaml
triggers:
- name: sync-problem
  condition: app.status.operationState.phase in ['Error', 'Failed', 'Succeeded']
  template: sync-operation-status-change
templates:
- name: sync-operation-status-change
  webhook:
    msteamswebhook:
      method: POST
      body: |
        {"title": "something"}
subscriptions:
- recipients:
  - webhook:msteamswebhook
  triggers: sync-problem
- recipients:
  - webhook:msteamswebhook

```

Is there anything I am doing wrong, or is that a bug?
I am using version 0.7.0

**Comment by Mr-istov** [comment]
Hello, from what I can see the `triggers` might be causing an issue, it expects to be a list.
Can you try modifying it to be like this, and then try if it works:
```yaml
subscriptions:
- recipients:
  - webhook:msteamswebhook
  triggers:
  - sync-problem
- recipients:
  - webhook:msteamswebhook
```
