### ISSUE TITLE
Notification on deployment success

### ISSUE THREAD

**Issue by juris** [argoproj-labs/argocd-notifications#173]
I couldn't find it in the docs, but is it possible to send notification when rollout actually happened, when all the new pods are in place and old pods are gone?
The closest thing I could get so far is .on-deployed trigger, but it notifies too early, when there's still something happening with the app.

**Comment by Zava2012** [comment]
Hello!
During my experimentations with this tool I found a solution to wait before all pods will be started.
You can try this behavior and maybe it will help you. Here is a snippet of trigger from Helm Chart:
```
trigger.on-sync-succeeded: |
  - when: app.status.health.status == 'Healthy'
    oncePer: app.status.sync.status == 'Synced' and app.status.operationState.phase == 'Running'
```
But this trigger isn't handling the case when upgrading of Kubernetes cluster or, for example, manual deleting pod because ArgoCD starting to sync application and this event will trigger a notification. I had tried many options in addition to snipper above but without success.
It will be great if someone find a solution to fix this case.

Furthermore, `on-deployed` trigger behavior from documentation is triggering notifications for all of my applications after upgrading one of the applications or just restart of ArgoCD Notifications pod.

**Comment by juris** [comment]
Hi @Zava2012 thanks for sharing your solution.

Btw, the following config (that oncePer thing) helped me to reduce notification amount, so now it's being triggered once per sync revision per app:
```
trigger.on-deployed: |
  - description: Application is synced and healthy. Triggered once per sync.
    oncePer: app.status.operationState.operation.sync.revision
    send:
    - app-deployed
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
