### ISSUE TITLE
More than 130 applications in ArgoCD triggering notifications about all of them

### ISSUE THREAD

**Issue by Zava2012** [argoproj-labs/argocd-notifications#179]
Hello!
In my ArgoCD (deployed in Kubernetes cluster) I have more than 130 applications. When I deployed ArgoCD Notifications (using Helm Chart) with `on-deployed` trigger from documentation, after new commit with changes for one application or ArgoCD Notifications pod restart, I had been got notifications about all of this applications.
Here is snippet from documentation:
```
trigger.on-deployed: |
  - description: Application is synced and healthy. Triggered once per commit.
    oncePer: app.status.sync.revision
    send:
    - app-deployed
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
After my experimentations I found a solution to handle this behavior. Here is my snippet:
```
trigger.on-deployed: |
  - when: app.status.health.status == 'Healthy'
    oncePer: app.status.sync.status == 'Synced' and app.status.operationState.phase == 'Running'
```
But this trigger isn't handling the case when upgrading of Kubernetes cluster or, for example, manual deleting any Pod because ArgoCD starting to sync application and this event will trigger a notification. I had been trying many options in addition to snipper above but without success.
To trigger notifications I'm using Default Subscription.

I saw an issue https://github.com/argoproj-labs/argocd-notifications/issues/60 about annotations limitation. 
Small discussion about this issue was here: #173

Maybe someone know workaround how to handle this behavior?
