### ISSUE TITLE
oncePer option bug

### ISSUE THREAD

**Issue by studypyth** [argoproj-labs/argocd-notifications#183]
Hi,All, i have issue with duplicate notifications, i am getting for each commit notification twice  I am using oncePer option, but i have no affect to problem.  Also this my configuration of trigger
```
  trigger.on-sync-running: |
    - when: app.status.operationState.phase in ['Running']
      oncePer: app.status.sync.revision
      description: Application is being synced
      send: [app-sync-running]

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      oncePer: app.status.sync.revision
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
And for debug i changed template  to
```
      Debug: {{html .app.metadata.name}}  {{html .app.status.operationState.syncResult.revision}} {{html .app.status.sync.revision}}
```
And i received this messages 2 notifications in telegram for on-sync-running, as i see oncePer option wasnt worked

```
Debug: develop-devops-loki  <no value> 35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9
Debug: develop-devops-loki  <no value> 35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9
```
And duplicate message for on-sync-succeeded
```
Debug: develop-devops-loki  35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9 35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9
Debug: develop-devops-loki  35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9 35f3d95bdfe235ebfc9e736fa2ebb0945d6edfa9
```
