### ISSUE TITLE
How to set .context.argocdUrl

### ISSUE THREAD

**Issue by jbaskeen** [argoproj-labs/argocd-notifications#187]
Is there a support way to set the value of `.context.argocdUrl` as shown [in the template documentation](https://argocd-notifications.readthedocs.io/en/stable/services/slack/#templates)? The reference always resolves as localhost:4000 which does not appear to be useful. Can this be configued?

**Comment by caueasantos** [comment]
Give a try on that

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
    argocdUrl: https://argocd.foo.net
    service.slack: |
       token: $token
```

**Comment by ryota-sakamoto** [comment]
HI @jbaskeen 
You can use `context` to set any values.
see https://argocd-notifications.readthedocs.io/en/stable/templates/

**Comment by jbaskeen** [comment]
Thanks @ryota-sakamoto and @caueasantos. I was confused by the documentation but now it is clearer. So we basically have to define `context` and the child string config ourselves, as needed.

For others that might come across this, the format is below which can be achieved with a patch to `argocd-notification-cm`.

    $ CLUSTER="triskellion"
    $ oc patch configmap argocd-notifications-cm --type='json' -p='[{"op": "add", "path": "/data/context","value":"argocdInstance: '"$CLUSTER"'\nfoo: bar"}]'

The config map will be:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |-
    argocdInstance: triskellion
    foo: bar
...
```

Then references within a template can be `{{.context.argocdInstance}}` or `{{.context.foo}}` etc.
