### ISSUE TITLE
Failed to notify recipient for Slack/telegram/email please help me to setup

### ISSUE THREAD

**Issue by denist-huma** [argoproj-labs/argocd-notifications#196]
1. For Slack I got app token, and have a private channel, but bot is not a member, maybe this is a reason.
2. For Telegram I created private channel and made my bot an admin. Switched to public - still the same.
3.  **not anymore** I don't get why * notification service 'email' is not supported* I used the Templates from the catalog

#### Install Argo CD Notifications

    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/release-1.0/manifests/install.yaml
#### Install Triggers and Templates from the catalog

    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/release-1.0/catalog/install.yaml

#### Register notification services

    $ kubectl -n argocd patch secret argocd-notifications-secret --patch-file argocd-notifications-secret.yaml 
    secret/argocd-notifications-secret patched

    $ kubectl -n argocd patch cm argocd-notifications-cm --patch-file argocd-notifications-cm.yaml 
    configmap/argocd-notifications-cm patched

#### Subscribe to notifications

by adding the notifications.argoproj.io/subscribe.on-sync-succeeded.slack annotation to the Argo CD application or project:

    kubectl patch app ppserver -n argocd -p '{"metadata": {"annotations": {"notifications.argoproj.io/subscribe.on-sync-succeeded.telegram":"Argo Cd Notifications", "notifications.argoproj.io/subscribe.on-sync-succeeded.slack":"phoenix-argo"}}}' --type merge
    kubectl patch app ppserver -n argocd -p '{"metadata": {"annotations": {"notifications.argoproj.io/subscribe.on-sync-succeeded.email.gmail":"my@email.com"}}}' --type merge

#### Troubles

    time="2021-03-09T16:02:21Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{email my@email.com}'" app=argocd/ppserver
    time="2021-03-09T16:02:21Z" level=error msg="Failed to notify recipient {email my@email.com} defined in app argocd/ppserver: notification service 'email' is not supported" app=argocd/ppserver
    time="2021-03-09T16:02:21Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack phoenix-argo}'" app=argocd/ppserver
    time="2021-03-09T16:02:21Z" level=error msg="Failed to notify recipient {slack phoenix-argo} defined in app argocd/ppserver: channel_not_found" app=argocd/ppserver
    time="2021-03-09T16:02:21Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{telegram Argo Cd Notifications}'" app=argocd/ppserver
    time="2021-03-09T16:02:21Z" level=error msg="Failed to notify recipient {telegram Argo Cd Notifications} defined in app argocd/ppserver: Bad Request: chat not found" app=argocd/ppserver

**UPD 2021-mar-10** I go with [default-subscriptions](https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
    username: Argo CD # optional username
    icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png # optional icon for the message (supports both emoij and url notation)
  service.telegram: |
    token: $telegram-token
  service.email: |
    username: $email-username
    password: $email-password
    host: smtp.gmail.com
    port: 465
    from: $email-username
  subscriptions: |
    - recipients:
      - slack:phoenix-argo
      - email:my@email.com
      - telegram:Argo Cd Notifications
      triggers:
      - on-sync-status-unknown
      - on-sync-failed
      - on-health-degraded
      - on-deployed
      - on-sync-succeeded
```

### Result

```log
time="2021-03-10T15:22:45Z" level=error msg="Failed to notify recipient {slack phoenix-argo} defined in app argocd/ingress-controller: channel_not_found" app=argocd/ingress-controller
time="2021-03-10T15:22:45Z" level=error msg="Failed to notify recipient {email my@email.com} defined in app argocd/ingress-controller: 534 5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor XXXXXXXXXX- gsmtp" app=argocd/ingress-controller
time="2021-03-10T15:22:45Z" level=error msg="Failed to notify recipient {telegram Argo Cd Notifications} defined in app argocd/ingress-controller: Bad Request: chat not found" app=argocd/ingress-controller
```

### what to do next?

- gmail 2FA not let me send, ok
- slack: I am not an admin, TL installed bot @phoenixargo in this channel. As I can see message is `added an integration to this channel: phoenix-argo.` @phoenixargo has `chat:write`, `chat:write.customize` scopes.
- phoenix-argo is private
- telegram - same `chat not found` by its name "Argo Cd Notifications"
-  Argo Cd Notifications is public channel, bot is admin there.
