### ISSUE TITLE
Global recipients

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argocd-notifications#2]
Support specifying recipients in the `argocd-notifications-cm`  ConfigMap. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    recipients:
      - slack:my-team
      - email:my-team@mycompany.com
```
