### ISSUE TITLE
Subscribe to all triggers at once

### ISSUE THREAD

**Issue by eddycharly** [argoproj-labs/argocd-notifications#202]
Is it possible to subscribe to all triggers at once ?
Right now i have:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: core-platform-team
    notifications.argoproj.io/subscribe.on-deployed.slack: core-platform-team
    notifications.argoproj.io/subscribe.on-health-degraded.slack: core-platform-team
    notifications.argoproj.io/subscribe.on-sync-failed.slack: core-platform-team
    notifications.argoproj.io/subscribe.on-sync-running.slack: core-platform-team
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: core-platform-team
```

Something like this maybe ?
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.slack: core-platform-team
```

**Comment by alexmt** [comment]
This is already supported by "default" triggers: 

https://github.com/argoproj-labs/argocd-notifications/blob/64cbb1aeec3949d433208d686aeef6128147f327/docs/argocd-notifications-cm.yaml#L39-L41

You can specify required triggers using `defaultTriggers` field of `argocd-notifications-cm` ConfigMap as subscribe as you proposed: `notifications.argoproj.io/subscribe.slack: core-platform-team`

**Comment by eddycharly** [comment]
Thanks @alexmt !

If I understand correctly `defaultTriggers` are global or is there something similar at the service level ?

I mean default triggers could be different when sending github statuses or slack notifications.

**Comment by alexmt** [comment]
Yes, at this point `defaultTriggers` are global and agree that it makes sense to split triggers by service. We could introduce `defaultTrigger.<service>` setting. E.g. 


```yaml
defaultTriggers.slack: 
     - on-sync-status-unknown 
```

**Comment by eddycharly** [comment]
Something along those lines would be great indeed =)

**Comment by sergeyshaykhullin** [comment]
@alexmt I tried this default triggers with 1.0.14 helm chart:

```yaml
triggers:
    defaultTriggers: |-
      - on-sync-succeeded
      - on-deployed
      - on-health-degraded
      - on-sync-failed
      - on-sync-running
      - on-sync-status-unknown
   ... triggers
```

```yaml
annotations:
  notifications.argoproj.io/subscribe.slack: test
```

And nothing works... Single-annotated trigger is working fine

Error from notifications-controller:

```
Recovered from panic: runtime error: index out of range [1] with length 1\ngoroutine 2620 [running]:\nruntime/debug.Stack(0xc0015770b0, 0x1dd0320, 0xc000f40240)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processQueueItem.func1(0xc0001d6e40, 0x1be97c0, 0xc000addfd0)\n\t/src/controller/controller.go:320 +0x88\npanic(0x1dd0320, 0xc000f40240)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/argoproj-labs/argocd-notifications/pkg/subscriptions.Annotations.iterate(0xc000d8fd70, 0xc0015773c0)\n\t/src/pkg/subscriptions/annotations.go:42 +0x293\ngithub.com/argoproj-labs/argocd-notifications/pkg/subscriptions.Annotations.GetAll(0xc000d8fd70, 0xc0005ee480, 0x6, 0x8, 0xc000d8fd70)\n\t/src/pkg/subscriptions/annotations.go:110 +0x8c\ngithub.com/argoproj-labs/argocd-notifications/controller.(*notificationController).getSubscriptions(0xc0001d6e40, 0xc0003c2da0, 0xc000d8fce0)\n\t/src/controller/controller.go:254 +0x1c5\ngithub.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processApp(0xc0001d6e40, 0xc0003c2da0, 0xc0004cdab0, 0x1, 0x1)\n\t/src/controller/controller.go:171 +0x19c\ngithub.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processQueueItem(0xc0001d6e40, 0x203001)\n\t/src/controller/controller.go:346 +0x451\ngithub.com/argoproj-labs/argocd-notifications/controller.(*notificationController).Run.func1()\n\t/src/controller/controller.go:133 +0x36\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005ec380)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005ec380, 0x2161a40, 0xc00077e930, 0x406301, 0xc000e2aa20)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005ec380, 0x3b9aca00, 0x0, 0xc000582f01, 0xc000e2aa20)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc0005ec380, 0x3b9aca00, 0xc000e2aa20)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).Run\n\t/src/controller/controller.go:132 +0x119
```
