### ISSUE TITLE
Using oncePer on annotations with prefix

### ISSUE THREAD

**Issue by jeromeky** [argoproj-labs/argocd-notifications#222]
Hi there,

I'm using annotations to add more details to each of my applications, so I can reuse that in my template.

e.g

```
Kind: Application
metadata:
  annotations:
    foo.bar/commit: abc123
    foo.bar/author: jerome
```

I have no trouble to use it in my template like that `{{ index .app.metadata.annotations "foo.bar/commit" }}`

However, I'm not sure how I could reuse these in the trigger section.

I already tried

```
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.metadata.annotations.foo.bar/commit
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

or

```

  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.metadata.annotations.commit
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

But none of these work.

Is there a way to use annotation that has a prefix in the trigger section?

I'm using annotations to add more details about the commit as the CI/CD is the one doing the commit to a repo that ArgoCD is monitoring.

Thanks for your help.
