### ISSUE TITLE
I get this log message: `notification service 'slack' is not supported`

### ISSUE THREAD

**Issue by ngandriau** [argoproj-labs/argocd-notifications#229]
Hi, I hope you are doing well.
I am experimenting `argocd-notification` on an `EKS` cluster.
I use argocd `v1.8.7+eb3d1fb` and argocd-notification v1.0.2

I am trying to get notification sent to my company's slack workspace
I have registered a slack application according to https://argocd-notifications.readthedocs.io/en/stable/services/slack/ and the app is registered to my targeted channel

I have then configured the `argocd-notifications-cm` config map and the `argocd-notifications-secret` and registered my argo application to send notification when `on-sync-succeeded`.

When I sync my app, I don't get notification in slack.
Looking at the log of the pod `argocd-notifications-controller-*****` I see this message:
```
time="2021-03-31T08:02:07Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack tc-jenkins-aws}'" app=argocd/cloudy-emily-dev
time="2021-03-31T08:02:07Z" level=error msg="Failed to notify recipient {slack tc-jenkins-aws} defined in app argocd/cloudy-emily-dev: notification service 'slack' is not supported" app=argocd/cloudy-emily-dev
```

If I execute this command on the pod: argocd-notifications-controller, I get an error, but I check my `yaml` files for the `ConfigMap` and the `Secret` and they look valid.
```
$kubectl -n argocd  exec -it argocd-notifications-controller-84ccc64f96-pf42v \
>   /app/argocd-notifications trigger get
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
failed to parse config: error converting YAML to JSON: yaml: line 2: did not find expected '-' indicator
```

Can you help me figure out what I did wrong?
Thanks in advance for your help

**Comment by ngandriau** [comment]
Hi @ryota-sakamoto 
I installed according to quickstart of release: https://github.com/argoproj-labs/argocd-notifications/releases/tag/v1.0.2.
Not sure what is `catalog`, can you try to explain to me.
Thanks

**Comment by ryota-sakamoto** [comment]
@ngandriau 
`catalog` is written in `Getting Started` that includes `triggers` and `templates`.
https://argocd-notifications.readthedocs.io/en/stable/

Would you install `catalog` and try again, please?

**Comment by ngandriau** [comment]
thanks for the explanation @ryota-sakamoto 
So I have installed the `template-catalog` with the command: `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.0.2/catalog/install.yaml`

my `ConfigMap` is:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    apiURL: https://api.slack.com/
    token: xoxb-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    username: ngandriau
    icon: https://avatars.githubusercontent.com/u/30269780?s=400&v=4
  subscriptions: |
    - recipients:
          - slack:tc-jenkins-aws
          triggers:
          - on-sync-succeeded

---

apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  token: xoxb-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

thanks
