### ISSUE TITLE
template 'app-sync-succeeded' is not supported

### ISSUE THREAD

**Issue by dangreenlee** [argoproj-labs/argocd-notifications#236]
I’ve deployed ArgoCD-notifications via Helm Dependency using ArgoCD, I have the slack-secret available in the cluster and my logs show no errors connecting w/ slack API but when the controller goes to execute a notification I receive this error like this with all applications: 

```
ime="2021-04-06T20:47:16Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack deploy}'" app=argo-cd/guestbook
time="2021-04-06T20:47:16Z" level=error msg="Failed to notify recipient {slack deploy} defined in app argo-cd/guestbook: template 'app-sync-succeeded' is not supported" app=argo-cd/guestbook
```

I’m using the default template from the catalog. My default subscriptions are pretty simple:
```
 subscriptions:
    - recipients:
      - slack:deploy
      triggers:
      - on-sync-status-unknown
      - on-sync-running
      - on-sync-succeeded
      - on-deployed
```
Unsure what else I could look at to try and resolve this. Thank you.
