### ISSUE TITLE
Incorrect rbac permissions for configmap/secret resources

### ISSUE THREAD

**Issue by sboschman** [argoproj-labs/argocd-notifications#237]
The change introduced in #199 blocks the controller from refreshing / listing the secrets and configmaps. This prevents any notifications to be sent after a configmap/secret change.

I believe it has to do with this description in the official k8s docs:
> A given Kubernetes server will only preserve a historical list of changes for a limited time. Clusters using etcd3 preserve changes in the last 5 minutes by default. When the requested watch operations fail because the historical version of that resource is not available, clients must handle the case by recognizing the status code 410 Gone, clearing their local cache, **performing a list operation**, and starting the watch from the resourceVersion returned by that new list operation.

I can't find a definite answer in the docs, but I think that list and resourceNames are mutual exclusive in the rbac role definition. The verbs get, list, watch, etc specify allowed api resource endpoints, and a list will always return all elements, there is afaik no concept of returning only a partial result based on permissions. Same for listing namespaces, you can list all namespaces or you are not allowed to list namespaces, you can't list only the namespaces you have permission to access.

A kustomize workaround:
```patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: argocd-notifications-controller
    path: argocd-notifications-controller-role.yaml
```
```
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - list
- op: add
  path: "/rules/-"
  value:    
    apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - list
```
