### ISSUE TITLE
Github service not working

### ISSUE THREAD

**Issue by AlexDHoffer** [argoproj-labs/argocd-notifications#247]
Installed via Helm (latest version), here are my files:

argocd-notifications-cm

````
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.github: |
    appID: [appid]
    installationID: [installationid]
    privateKey: $github-privateKey
````

argocd-notifications-secret

````
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  github-privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    [snip]
    -----END RSA PRIVATE KEY-----
````

But the logs for ArgoCD Notifications report:

``time="2021-04-09T21:35:41Z" level=warning msg="Failed to parse new settings: service type 'github' is not supported"``

I believe I have followed the instructions correctly. What am I missing?
