### ISSUE TITLE
Support sending the generic webhook request. 

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argocd-notifications#25]
Support sending the generic HTTP request with the ability to generate request body using a template. This feature allows provides a way to quickly integrate notification service that does not have first-class support.

The notification service is not necessary to send messages to a human.  It might be Jenkins webhook that triggers a post-deployment test.

The `argocd-notifications-secret` allows defining named webhooks under new `webhooks` field. Each webhook has the url and optional list of headers.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
      - name: jenkins
        url: https://my-jenkins/webhook
        headers:
          - name: Authorization
            value: <secret-value-here>
type: Opaque
```

The webhook can be referenced using `webhook:<name>` in `argocd-notifications.argoproj.io` annotation:

```yaml
metadata:
  annotations:
    on-sync-succeeded.recipients.argocd-notifications.argoproj.io: webhook:jenkins
```

The notification template should have the `webhook` field that allows specifying request method and body.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
    templates:
      - name: jenkins-webhook
        webhook:
          jenkins:
            method: POST # optional, POST is default value
            body: | {
                  "test": "test"
            }
```
