### ISSUE TITLE
Listen and trigger when application change from Degraded to Healthy

### ISSUE THREAD

**Issue by joaocarvalhowd** [argoproj-labs/argocd-notifications#254]
Does someone know how to do that?

I have tried:

```
- description: Application it's healthy again
      send:
      - app-health-again
      oncePer: app.status.health.status
      when: app.status.health.status == 'Healthy'
```

**Comment by joaocarvalhowd** [comment]
@ryota-sakamoto Someone could help me?

**Comment by IuryAlves** [comment]
Hey @joaocarvalhowd 

I also had the same issue and I fixed by adding the following trigger and template:

```yaml
templates:
  # On app status change
  - name: on-status-change
    title: Application {{.app.metadata.name}} is {{.app.status.health.status}}
    body: |
      {{if eq .context.notificationType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is {{.app.status.health.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
triggers:
  - name: on-healthy
    enabled: true
    oncePer: app.status.health.status
    condition: app.status.health.status == 'Healthy'
    template: on-status-change
```

**Note:** I am using Argo Notifications `0.7.0`
