### ISSUE TITLE
is it possible to send notifications to different Teams channels per application in argoCD?

### ISSUE THREAD

**Issue by shivamsood** [argoproj-labs/argocd-notifications#257]
I would want to configure notifications to Teams different channels for different applications. For example I have 2 applications A and B. I want to send notifications for app A to channel 1 and notifications for app B to channel 2.

**Comment by ryota-sakamoto** [comment]
Hi @shivamsood 
You can send notifications for different channels as follows.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.teams: |
    recipientUrls: 
      channelA: $channel-a-url
      channelB: $channel-b-url
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelA
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelB
```

**Comment by shivamsood** [comment]
Hi @ryota-sakamoto 

I did try that approach. I am using latest helm charts for argocd-notifications

This is how my values file look like 

```
secret:
  # Whether helm chart creates controller secret
  create: true

  items:
    channel-teams-urlA: URL_A
    channel-teams-urlB: URL_B
    
notifiers:
# For more information: https://argocd-notifications.readthedocs.io/en/stable/services/overview/
  service.teams: |
    recipientUrls: 
      channelNameA: $channel-teams-urlA
      channelNameB: $channel-teams-urlB
      
      
subscriptions:
  # For more information: https://argocd-notifications.readthedocs.io/en/stable/subscriptions/

  # subscription for on-sync-status-unknown trigger notifications
  - recipients:
    - teams:channelNameA
    - teams:channelNameB
    triggers:
    - on-sync-status-unknown
    - on-created
    - on-deleted
    - on-deployed
    - on-health-degraded
    - on-sync-failed
    - on-sync-running
    - on-sync-succeeded

**Comment by shivamsood** [comment]
my application manifest looks like this 

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelNameB
    notifications.argoproj.io/subscribe.on-sync-running.teams: channelNameB
    notifications.argoproj.io/subscribe.on-created.teams: channelNameB
    notifications.argoproj.io/subscribe.on-deleted.teams: channelNameB
    notifications.argoproj.io/subscribe.on-sync-status-unknown.teams: channelNameB
    notifications.argoproj.io/subscribe.on-deployed.teams: channelNameB
    notifications.argoproj.io/subscribe.on-health-degraded.teams: channelNameB
    notifications.argoproj.io/subscribe.on-sync-failed.teams: channelNameB
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

**Comment by shivamsood** [comment]
on sync operation this send messages to both the channels. which is not why my use case is

**Comment by ryota-sakamoto** [comment]
@shivamsood 
The subscriptions is globally so I think you don't set subscriptions field and you set annotations, then you can send notification different channel and trigger.
```
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelA
    notifications.argoproj.io/subscribe.on-sync-failed.teams: channelB
```
