### ISSUE TITLE
Slack notifications with ApplicationSet controller

### ISSUE THREAD

**Issue by legigor** [argoproj-labs/argocd-notifications#270]
## Summary 

I've added the notification `notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-activity` to the template section of the `ApplicationSet` definition. On sync it started bombing my Slack with duplicated notifications. On the ArgoCD GUI I noticed the annotations for the selected Application been updated all the time with something like notification already sent, then this notification disappeared, then another Slack nmessage arrived, annotation updated and disappeared again and again.

The AppSet config looks like

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: the-cluster
spec:
  generators:
    - git:
        repoURL: git@github.com:company/the-cluster.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-activity      
    spec:
      project: default
      source:
        repoURL: git@github.com:company/the-cluster.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
```

## Diagnostics

What Kubernetes provider are you using? 
- Latest available on Azure AKS

What version of Argo CD and Argo CD Notifications are you running? 
- Argo CD 2.0
- Argo CD Notifications v1.0.2

```
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:03Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Start processing" app=argocd/ops
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
