### ISSUE TITLE
argocd-notifications cannot reach argocd-repo-server because of NetworkPolicy

### ISSUE THREAD

**Issue by timoschwarzer** [argoproj-labs/argocd-notifications#294]
## Summary 

Argo CD Notifications cannot connect to argocd-repo-server because of the recently added `NetworkPolicy` resources in Argo CD.

Applying an additional policy fixes this problem:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-repo-server-network-policy-argocd-notifications
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-notifications
    ports:
    - port: 8081
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  policyTypes:
  - Ingress
```

This policy should probably be added to Argo CD Notifications. Alternatively, the [Argo CD NetworkPolicy](https://github.com/argoproj/argo-cd/blob/master/manifests/base/repo-server/argocd-repo-server-network-policy.yaml) should include a selector for argocd-notifications.

## Diagnostics

What Kubernetes provider are you using?

K3s 1.20.6+k3s1

What version of Argo CD and Argo CD Notifications are you running? 

- Argo CD 2.0.3
- Argo CD Notifications 1.1.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
