### ISSUE TITLE
feat: add message aggregation feature by slack threads API

### ISSUE THREAD

**Issue by MasayaAoyama** [argoproj-labs/argocd-notifications#319]
# Summary

Support message aggregation feature by slack threads API.
impl idea: https://github.com/argoproj/notifications-engine/pull/40

![image](https://user-images.githubusercontent.com/8783194/127752362-0423ffb3-4bf8-4b7a-a922-1fcc70b6d376.png)

# Use Cases

If we have a lot of microservices, we'll get a lot of Slack messages. In the current implementation, it is difficult to read because it cannot be aggregated in threads.

I would like to add a feature to aggregate to threads under specific conditions which are git commit hash, application name. In addition, I would like to add a feature to broadcast to the channel under specific conditions.

Details:

If we can aggregate with git commit hash, we can easily read the messages even when multiple microservices are updated with the same commit.

If we can aggregate with the application name, we can easily read the status history, change history, and the last status of each application. In addition, the sync status fails and the message can be broadcast to the channel.

# Implementation idea

We will be able to specify `groupingKey` at data.template.slack in `argocd-notification-cm` ConfigMap. `groupingKey` can be templated by placeholders. so we can flexibly describe conditions.

 In addition, for each template by `notifyBroadcast` setting.

Furthermore, we can choose whether or not to broadcast to the channel at each template, so we can set up broadcast only at sync-fail.

Furthermore, since it is possible to set whether to broadcast for each template with `notifyBroadcast` field, it is also possible to broadcast only at template.app-sync-failed.

e.g.
* `{{.app.status.sync.revision}}`
    * => cac7f13ff253f63cfe53ccafe27af4a6b936d14a
* `{{.app.status.sync.revision}}-{{.app.metadata.name}}`
    * => cac7f13ff253f63cfe53ccafe27af4a6b936d14a-myapp
* `{{time.Now().Months()}}-{{time.Now().Days()}}-{{.app.metadata.name}}`
    * => 08-01-myapp

```yaml
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  template.app-sync-status: |
    message: "Success"
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "color": "#18be52",
          "fields": [{
            "title": "Commit",
            "value": "{{.app.status.sync.revision}}",
            "short": false
          }]
        }]
      groupingKey: "{{.app.status.sync.revision}}"
      notifyBroadcast: false
  template.app-sync-failed: |
    message: "Failed"
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "color": "#ff0000",
          "fields": [{
            "title": "Commit",
            "value": "{{.app.status.sync.revision}}",
            "short": false
          }]
        }]
      groupingKey: "{{.app.status.sync.revision}}"
      notifyBroadcast: true
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
