### ISSUE TITLE
double notification from argo

### ISSUE THREAD

**Issue by nohant** [argoproj-labs/argocd-notifications#338]
## Summary 

We want to receive a single notification every time we deploy a new release of an application.
instead, we receive two notification for every release.

## Diagnostics

What Kubernetes provider are you using? 
`we have our own cluster. 1.18 k8s version.`

What version of Argo CD and Argo CD Notifications are you running? 
```
argocd tag: v2.0.4
argo notification: v1.1.1
```

# Paste the logs from the notification controller
logs are a bit useless, they just repeat this:
```
argocd-notifications-controller-59dfb8d44b-psmpw argocd-notifications-controller time="2021-09-13T09:59:37Z" level=warning msg="Controller has stopped."
argocd-notifications-controller-59dfb8d44b-psmpw argocd-notifications-controller time="2021-09-13T09:59:37Z" level=warning msg="Controller is running."
```
## Configuration:
we have a monorepo configuration, 
so every time we update one app, we change every "repository" status for every app. 
in order to receive notification for the single app we used status.summary.images as onceper.

```
   trigger.on-deployed: |
     - description: Application is synced and healthy. Triggered once per commit.
       oncePer: app.status.summary.images
       send:
       - app-deployed
       when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status == 'Synced'

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
