### ISSUE TITLE
Addition of new trigger: on-health-healthy

### ISSUE THREAD

**Issue by pentago** [argoproj-labs/argocd-notifications#341]
# Summary

Introducing new trigger: `on-health-healthy`

# Use Cases

When using HPA and deploying apps, there's a short period of time until HPA collects metrics and the app is fully healthy and in green.

Meanwhile, notifications about degraded health are sent to notification channels and there's no new notification once HPA is healthy and the whole application is in green. This leaves the notification observer wondering if an app is entire time degraded when in reality degraded state lasted for about 10 seconds.

This new trigger should accompany `on-health-degraded` trigger and better represent situation in clusters.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Zava2012** [comment]
Hello!
I have a similar behavior: after approximately 10 seconds when the application has a Healthy status I will get a notification that the application changed status from Healthy -> Degraded without notification when the application will get Healthy status again.

In ArgoCD Application Controller debug logs I've found the root cause of that:
`The HPA was unable to compute the replica count: did not receive metrics for any ready pods.`

And this is a logical behavior for HPA. But, I think, ArgoCD Notifications is not handling this behavior of HPA that's why we will get redundant notifications in this order:
- `Progressing -> Healthy` - the first notification
- `Healthy -> Degraded (approximately after 10 seconds)` - the second notification

I'm using these triggers to get notifications:
```
triggers:
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.operationState.syncResult.revision
      send: [app-deployed]
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
```

Also, checked current behavior on ArgoCD Notifications v1.1.0 and v1.1.1. Everywhere is the same.

My expectations: when the application is using HPA controller then ArgoCD Notifications must wait before the controller will get necessary metrics from Metrics API (from Metrics Server component).

If my expectations is incorrect, please give me know)

**Comment by pentago** [comment]
I'm fine with notifications on degraded getting sent but would want healthy status notification right away when the app is healthy again, regardless of how quickly sent - if it's after 10 seconds, that's fine to me.

BUT, if ArgoCD can somehow poll HPA status and wait untill app is healthy, that would be even better.

**Comment by pentago** [comment]
@Zava2012  wouldn't hurt adding a 👍🏼  on the issue to move it up in prioritization a bit. :)

**Comment by mubarak-j** [comment]
would this trigger condition prevent sending the false alert? i.e wait 2 mins before sending degraded notifications

```yaml
  trigger.on-health-degraded: |
    - description: Application has degraded
      oncePer: app.status.sync.revision
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded' and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() >= 2
```
