### ISSUE TITLE
Allow sending notifications only after a period

### ISSUE THREAD

**Issue by eddycharly** [argoproj-labs/argocd-notifications#342]
For example, an helm repository might be unavailable for a few minutes, it would be nice to send a notification to alert the app is in an unknown state only if it is in this state for 10 minutes for example.

Maybe we can already do it though, the best i could come up with is this:
```
    - description: Application status is 'Unknown'
      when: app.status.sync.status == 'Unknown' and time.Now().Sub(time.Parse(app.status.conditions[0].lastTransitionTime)).Minutes() >= 10
      send:
        - app-sync-status-unknown
```

Not sure if accessing the `conditions` array item at index `0` is sage though.
