### ISSUE TITLE
docs: Webhook recipient in subscriptions only needs the webhook name

### ISSUE THREAD

**Issue by cquintana92** [argoproj-labs/argocd-notifications#354]
# Summary

According to [the docs](https://argocd-notifications.readthedocs.io/en/stable/subscriptions/), default subscriptions can be added by

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  subscriptions: |
    - recipients:
      - slack:test2
      - email:test@gmail.com
      triggers:
      - on-sync-status-unknown
```

In my case, I had the following configuration defined:

```yaml
data:
  service.webhook.something: |
    url: MY_WEBHOOK_URL
  subscriptions: |
    - recipients:
        - webhook:something
      triggers:
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-running
        - on-sync-status-unknown
        - on-sync-succeeded
```

And the logs complained about the `webhook` service not being supported:

```
"Failed to notify recipient {webhook something} defined in app MY_APP: notification service 'webhook' is not supported"
```

According to [the docs](https://argocd-notifications.readthedocs.io/en/latest/troubleshooting/#failed-to-notify-recipient), this line meant that the service had not been defined in the `argocd-notifications-cm` or a failure in parsing the settings. However, the service had been defined and the controller was not showing any error in parsing the settings.

After some trial and error, I found that I needed to make this change:

```diff
data:
  service.webhook.something: |
    url: MY_WEBHOOK_URL
  subscriptions: |
    - recipients:
-        - webhook:something
+       - something 
      triggers:
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-running
        - on-sync-status-unknown
        - on-sync-succeeded
```

I would have expected the correct value to be `webhook:something`, as the other recipients are `slack:test` or `email:test@test.com` (following the naming schema `<serviceType>:<serviceName>`).

Probably this could be illustrated with an example in order to avoid confusions while setting it up, as it's been a little bit "trial and error" until it worked (due to not knowing where exactly the issue was).

# Use Cases

It will be useful to anybody starting to work with this project who wants to set up some webhook notifications.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
