### ISSUE TITLE
Unable to inject secret in templates

### ISSUE THREAD

**Issue by musabmasood** [argoproj-labs/argocd-notifications#357]
Given that `mysecret` is a key in `argocd-notifications-secret`:

```yaml
kubectl get secret argocd-notifications-secret -o yaml

apiVersion: v1
data:
  mysecret: xxxxxxxx
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
```

I am unable to use `mysecret` inside my template:

```yaml
apiVersion: v1
data:
  context: |
    mysecret: $mysecret
  template.some-template: |
    message: |
      The secret is {{ .context.mysecret  }} <=== doesn't work
      The secret is $mysecret <======== doesn't work either
```

How can I inject `mysecret` into my templates?

_Use-case: The secret is needed in the payload body of a webhook._
