### ISSUE TITLE
Timeout for notification triggers

### ISSUE THREAD

**Issue by VA-PLE** [argoproj-labs/argocd-notifications#365]
Hello. I use argocd-notifications trigger:

```
trigger.on-sync-status-unknown: |
  - description: Application status is 'Unknown'
    send:
    - app-sync-status-unknown
    when: app.status.sync.status == 'Unknown'
```

Which notifies whether the helm chart (from the gitrepo) coincides with what is deployed in kub. Helm repositories and kube cluster are located in different regions and between them from time to time there are network delays. This leads to a false positive notification.

Please either increase the validation time of the inspection or provide tools to manually manage this latency.
