### ISSUE TITLE
Notification doesnot support service type 'github' 

### ISSUE THREAD

**Issue by RaviHari** [argoproj-labs/argocd-notifications#369]
## Summary 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.github: |
    appID: xxx
    installationID: xxx
    privateKey: $github-privateKey
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]
  template.app-sync-succeeded: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
```

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  github-privateKey: |
     -----BEGIN RSA PRIVATE KEY-----
     XXXXXXXXXXXXXXXXXX
     -----END RSA PRIVATE KEY-----
```

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo CD and Argo CD Notifications are you running? 

argocd:v2.1.7
argocd-notifications:v1.0.2

```
# Paste the logs from the notification controller

# Logs for the entire controller:
kubectl logs -n argocd deployment/argocd-notifications-controller

time="2021-12-01T04:56:21Z" level=warning msg="Failed to parse new settings: service type 'github' is not supported"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
