### ISSUE TITLE
ArgoCD Notifications do not allow MS Teams Application when deployed with helmchart

### ISSUE THREAD

**Issue by rufreakde** [argoproj-labs/argocd-notifications#376]
## Summary 
Installed ArgoCD Notifications Helmchart.
Created resources that are needed for notifications with MS Teams.
Failed with error:
```sh
argoproj.io/v1alpha1/Application
argocd
argocd-notifications-teams
 SyncFailed
error validating data: ValidationError(Application): missing required field "spec" in io.argoproj.v1alpha1.Application
```

## Diagnostics
What Kubernetes provider are you using? 
AWS

What version of Argo CD and Argo CD Notifications are you running? 

```sh
ArgoCD Notifications Helm Chart: 1.7.1
ArgoCD Helm Chart 2.1.0
```

Argo CD Declarative Setup:
```yaml
---
#  https://argocd-notifications.readthedocs.io/en/stable/services/teams/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams:  <Channel Name>
  name: argocd-notifications-teams
  namespace: argocd
---
#  https://argocd-notifications.readthedocs.io/en/stable/services/teams/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  service.teams: |
    recipientUrls:
      channelName: $channel-teams-url
  template.app-sync-succeeded
... # template for teams from guide
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
... # encrypted sealed secret bitnami
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: argocd-notifications
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.7.1
    helm:  #  https://artifacthub.io/packages/helm/argo/argocd-notifications
      releaseName: argocd-notifications-helm
      parameters:
        - name: cm.create
          value: "false"
        - name: cm.name
          value: argocd-notifications-cm
        - name: secret.create
          value: "false"
        - name: secret.name
          value: argocd-notifications-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.1.0
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

```

```
# Paste the logs from the notification controller
time="2022-01-26T16:19:15Z" level=info msg="serving metrics on port 9001"
time="2022-01-26T16:19:15Z" level=info msg="loading configuration 9001"
time="2022-01-26T16:19:15Z" level=warning msg="Controller is running."
time="2022-01-26T16:19:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:19:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:19:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:19:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:19:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:19:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:19:18Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:19:18Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:19:23Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:23Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:19:44Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:20:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:20:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:20:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:20:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:20:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:20:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:24Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:29Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:29Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:29Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:29Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=info msg="Processing skipped: sync status out of date" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:45Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=info msg="Processing skipped: sync status out of date" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:20:59Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:21:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:21:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:21:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:21:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:21:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:21:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:21:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:21:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:21:32Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:21:32Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:21:32Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:21:32Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:21:44Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:21:44Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:22:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:22:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:22:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:22:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:22:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:22:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:22:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:22:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:23:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:23:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:23:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:23:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:23:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:23:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:23:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:23:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:24:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:24:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:24:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:24:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:24:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:24:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:24:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:24:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:24:32Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:24:32Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
time="2022-01-26T16:24:32Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:24:32Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:24:32Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:24:32Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:25:15Z" level=info msg="Start processing" resource=argocd/bom-resolution
time="2022-01-26T16:25:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/bom-resolution
time="2022-01-26T16:25:15Z" level=info msg="Start processing" resource=argocd/cluster-scoped-config
time="2022-01-26T16:25:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/cluster-scoped-config
time="2022-01-26T16:25:15Z" level=info msg="Start processing" resource=argocd/sealed-secrets
time="2022-01-26T16:25:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/sealed-secrets
time="2022-01-26T16:25:15Z" level=info msg="Start processing" resource=argocd/argocd-notifications-application
time="2022-01-26T16:25:15Z" level=error msg="Failed to process: failed to unmarshal template app-sync-failed: error converting YAML to JSON: yaml: line 1: did not find expected key" resource=argocd/argocd-notifications-application
```

---

Main Application for cluster configuration: (with the error of teams application not having right spec even though it it the same as in the guide [here](https://argocd-notifications.readthedocs.io/en/stable/services/teams/))
<img width="1063" alt="Screenshot 2022-01-26 at 17 34 48" src="https://user-images.githubusercontent.com/28104368/151205646-03b63ef4-1883-4bfa-9480-17e74ac6a591.png">

Helm Chart for argocd notification (somehow in sync in detail screen bot not in sync in the Main Application screen)
<img width="863" alt="Screenshot 2022-01-26 at 17 35 13" src="https://user-images.githubusercontent.com/28104368/151205819-78ac7896-ad12-410b-aa14-1ad71191aa1c.png">

**Message from the maintainers**:
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by rufreakde** [comment]
# Setup ArgoCD-Notifications with ArgoCD Helm Chart
Okay it was a configuration Issue on my side I will post the solution how to correctly setup the helm chart:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: argocd-notifications
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.7.1
    helm:  #  https://artifacthub.io/packages/helm/argo/argocd-notifications
      releaseName: argocd-notifications-helm
      parameters:
        - name: cm.create
          value: "false"
        - name: cm.name
          value: "argocd-notifications-cm"
        - name: secret.create
          value: "false"
        - name: secret.name
          value: "argocd-notifications-secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSync=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  context: |
    argocdUrl: "localhost:8080"
  defaultTriggers: |
    - on-sync-status-unknown
    - on-sync-succeeded
    - on-sync-failed
    - on-health-degraded
  service.teams: |
    recipientUrls:
      msTeams: $channel-teams-url
  trigger.on-deployed: |
    - description: ...
  trigger.on-health-degraded: |
    - description: ...
  trigger.on-sync-failed: |
    - description: ...
  trigger.on-sync-running: |
    - description: ...
  trigger.on-sync-status-unknown: |
    - description: ...
  trigger.on-sync-succeeded: |
    - description: ...
  template.app-sync-succeeded: |
    email: ...
  template.app-health-degraded: |
    email: ...
  template.app-sync-status-unknown: |
    email: ...
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    channel-teams-url: <secret encrypted>
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
```
