### ISSUE TITLE
Slack bot - 

### ISSUE THREAD

**Issue by AlbertasG** [argoproj-labs/argocd-notifications#379]
## Summary 
Created notifications to slack and `slack-bot` with `token` and `signingSecret`
Notifications works, but slack commands e.g. /argocd list-subscription which requires `signingSecret` from Slack errors with output:
```
failed to verify request signature: secret "argocd-notifications-secret" not found
```
Secret is there, we are deploying with official helm chart.

Config map:
```
apiVersion: v1
data:
  context: "argocdUrl: \n"
  service.slack: |
    token: $slack-token
    signingSecret: $slack-signing-secret
```

Secret
```
apiVersion: v1
data:
  slack-signing-secret: BASE64ENCODEDSECRET
  slack-token: BASE64ENCODEDSECRET
kind: Secret
```

Tried to give direct secret values inside the `configMap` but still no luck. Anyone else experienced this issue?

## Diagnostics

What Kubernetes provider are you using? 
EKS 1.20
What version of Argo CD and Argo CD Notifications are you running? 
ArgoCD v2.1.7
ArgoCD Notifications v1.2.1

```
# Paste the logs from the notification controller
Slack-bot gives no  log output

# Logs for the entire controller:
kubectl logs -n argocd deployment/argocd-notifications-controller
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
