### ISSUE TITLE
Get Helm values or annotations

### ISSUE THREAD

**Issue by joaogl** [argoproj-labs/argocd-notifications#383]
# Summary

Hey,
There should be a way to get helm values that were overrided in the app installation, or to access the application annotations.

# Use Cases

I would use this for passing data that I want to use later in the notifications.
For instance, my current application is as follows:
````
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "auth-${PR}"
  namespace: argocd
  annotations:
    myapps.com/url: "${PR}.myapps.com"
    notifications.argoproj.io/subscribe.discord.discord: ""
    notifications.argoproj.io/subscribe.on-deployed.discord: ""
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: "charts/app1"
    repoURL: git@github.com:my-apps/app1.git
    targetRevision: HEAD
    helm:
      values: |
        ingress:
          host: ${PR}.myapps.com
      version: v3
  destination:
    namespace: "${PR}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
````

Using this, I cannot access neither the annotation myapps.com/url nor the helm ingress.host value.
I know there's a way to access the helm values `{{(call .repo.GetAppDetails).Helm.GetParameterValueByName "ingress.host"}}` but for some super wierd reason I get back the Helm default value and not the overrided value rendering this feature pretty useless to me.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
