### ISSUE TITLE
Add parameter to disable link previews for links in Telegram messages

### ISSUE THREAD

**Issue by AleksandrTitov** [argoproj-labs/argocd-notifications#405]
# Summary

Telegram has possibility to disable link previews in messages using option [disable_web_page_preview](https://core.telegram.org/bots/api#sendmessage). I offer to add this parameter to the Telegram service configuration.

My example with parameter `disableWebPagePreview`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: <config-map-name>
data:
  service.telegram: |
    token: $telegram-token
    disableWebPagePreview: false
```

# Use Cases

This option is useful when you want to keep your messages clear, without additional useless informations.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
