### ISSUE TITLE
Feature: templates - enable transforming SSH git urls into user-friendly HTTPS

### ISSUE THREAD

**Issue by queil** [argoproj-labs/argocd-notifications#41]
Currently if using `.app.spec.source.repoURL` in message templates the URL is rendered as it is. So if it's a SSH git URL then Slack renders it as:
```
git@your.server.com:path/to/repo.git
``` 
It would be cool to be able to transform the URL into a HTTPS form:
```
https://your.server.com/path/to/repo
```

as it's user-friendly and more importantly navigable.

**Comment by SPFZ** [comment]
@queil I assume this could be quite complicate because of all the different format that exist for git urls. You would need some kind of conversion rules to make it work.

I believe a quick and easy fix could be to specify the https url as metadata when you define your app:

```yaml
# for declarative setup https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  repoURLhttps: https://your.server.com/path/to/repo
...
```

and then in your template you might be able to use `{{.app.metadata.repoURLhttps}}`.

I am not 100% that this works and I can not test this at the very moment but I would give it a try.
