### ISSUE TITLE
Support using message attachments for slack notifications

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argocd-notifications#6]
The [attachements](https://api.slack.com/messaging/composing/layouts#attachments) slack feature allows creating much more readable messages.

The notification template configuration should have an optional notification service-specific field that allows using the service-specific features. 

```yaml
  templates:
      - name: app-sync-status
        title: Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
        body: |
          Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
          Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
        slack: # used only if notification is sent to slack
          attachements:
            - title: Application {{.app.metadata.name}}
              title_link: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
              ...
```
