### ISSUE TITLE
Sync succeeded and status healthy condition - too many notifications

### ISSUE THREAD

**Issue by Mokto** [argoproj-labs/argocd-notifications#60]
Hi,

I would like to receive a notification when my environment is entirely ready, so I decided to use :

```
    triggers:
      - name: frontend
        condition: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
        template: frontend-sync-succeed
        enabled: true
```

It works well the first time, I only receive my notification when everything is healthy.
But if I manually kill a pod in the deployment (or if Kubernetes kills it for any reason), the pod is recreated and I receive the notification a second time.

I would like to receive a notification only for the first healthy status after a new sync.
Is there a way to do that ?
Thanks.

**Comment by alexmt** [comment]
Hello @Mokto ,

I think this is happening because application health status changes from 'Healthy' to `Progressing`  and then back to `Healthy`. In this case, notification is sent twice correctly.

Sounds like you want to send a notification when a particular condition met once for a commit. This is not supported right now. We could introduce a trigger setting, e.g. `oncePer`:

```yaml
    triggers:
      - name: frontend
        condition: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
        template: frontend-sync-succeed
       ## oncePer returns a unique key that is used to avoid sending the same notification again per key.
       ## e.g. notify that app is health and running one for each commit
        oncePer: app.status.sync.revision
```

The problem is that only storage we have it an annotation of Argo CD application. So argocd-notfication can "remember" only limited number of such keys ( I guess < 100 ).  However, it is not a big problem and should cover most of use cases.
