### ISSUE TITLE
Add `kustomization.yaml`

### ISSUE THREAD

**Issue by nikolay** [argoproj-labs/argocd-notifications#63]
Adding a simple `kustomization.yaml` would allow people to incorporate ArgoCD Notifications in their existing `kustomization.yaml` without having to use Git submodules or copy the existing manifests into their projects.

**Comment by muenchdo** [comment]
These already exist [here](https://github.com/argoproj-labs/argocd-notifications/blob/master/manifests/bot/kustomization.yaml) (with bot) and [here](https://github.com/argoproj-labs/argocd-notifications/blob/master/manifests/bot/kustomization.yaml) (controller only).

I use them in my kustomization for deploying Argo CD like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-1.4
  - github.com/argoproj-labs/argocd-notifications//manifests/bot?ref=v0.6.0

[...]
```
