### ISSUE TITLE
URL of Argo instance is incorrect

### ISSUE THREAD

**Issue by cookandy** [argoproj-labs/argocd-notifications#64]
Hello,

I am using ArgoCD `v1.4.2+48cced9` along with ArgoCD Notifications `v0.6.0`.

For ArgoCD, I have configured the URL as follows: 

```yaml
apiVersion: v1
data:
  url: https://mydomain.test
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```

However, when receiving the ArgoCD slack notifications, I see `https://localhost:4000` as the Argo URL.

```
Sync operation details are available at: https://localhost:4000/applications/secrets?operation=true
```

Can anyone tell me how the [`argocdUrl`](https://github.com/argoproj-labs/argocd-notifications/blob/41f94860215afa8e10e9a6a620b007e5c12e22af/cmd/controller.go#L27) variable is set? Thanks!
