### ISSUE TITLE
is there a way to add the cluster name as context for slack notication?

### ISSUE THREAD

**Issue by renperez** [argoproj-labs/argocd-notifications#67]
I want to add the cluster name on my slack notification. is there a way to add that? I was able to add the context for argocd url but was wondering if i can add the cluster name as well, since we are using argo for multiple cluster.

**Comment by alexmt** [comment]
Hello @renperez ,

Yes, context might contain any key, not just `argocdUrl`. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  config.yaml: |
    context:
      argocdUrl: <argocd-url>
      clusterName: <clusterName>
```

The value might be used as `{{.context.clusterName}}`
