### ISSUE TITLE
Webhook URL ends with suffix /

### ISSUE THREAD

**Issue by bclermont** [argoproj-labs/argocd-notifications#70]
My webhook can't ends with `/`

```
time="2020-04-06T11:01:41Z" level=error msg="Failed to notify recipient webhook:slack defined in app argocd/xxx: request to https://example.com/hooks/yyy/ has failed with error code 405 : " app=argocd/xxx
```

[that logic here](https://github.com/argoproj-labs/argocd-notifications/blob/ec2e5b8dbc474fd1daa11aa608919917a338632f/notifiers/webhook.go#L71)

force this behavior.

```
  notifiers.yaml: |
    webhook:
      - name: slack
        url: https://example.com/hooks/yyy
        headers:
          - name: Content-Type
            value: application/json
```

and

```
  config.yaml: |
    triggers:
      - name: on-sync-failed
        enabled: true
        template: xxx-app-sync-failed # issue 69
    subscriptions:
      - recipients:
          - webhook:slack
        triggers:
          - on-sync-failed
    templates:
      - name: xxx-app-sync-failed
        webhook:
          slack:
            method: POST
            body: |
              {
                "text": "!!!!",
                "channel": "cd"
              }
```

don't work. Users must

```
  notifiers.yaml: |
    webhook:
      - name: slack
        url: https://example.com/hooks
        headers:
          - name: Content-Type
            value: application/json
```

and

```
    templates:
      - name: xxx-app-sync-failed
        webhook:
          slack:
            method: POST
            path: yyy
            body: |
              {
                "text": "!!!!",
                "channel": "cd"
              }
```

but that leak the API key `yyy` to be in the `ConfigMap` instead of the `Secret`
