### ISSUE TITLE
Slack notifier - Icon and Username are not passing

### ISSUE THREAD

**Issue by gevalter** [argoproj-labs/argocd-notifications#71]
Hey guys i know its a new feature, tell me if you need hand in debugging this. we are not able to pass username and icon values in slack notifier. This is our argocd-notifications-secretyaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      icon: https://argoproj.github.io/argo-cd/assets/logo.png
      username: Argo-CD-Infra
type: Opaque
```
ArgoCD version: 1.5.0
argocd-notifications version: 0.6.1
Are we doing something wrong? we are able to receive the slack notifications but the icon and username does not change.
