### ISSUE TITLE
Is there a way to triggers when state condition not meet for certain time 

### ISSUE THREAD

**Issue by jfdumont** [argoproj-labs/argocd-notifications#75]
Hi,

my use case : i update an app 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    app-sync-succeeded.argocd-notifications.argoproj.io: "2020-04-19T15:38:14Z"
....
status:
  health:
    status: Progressing
...
  resources:
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: backend-dpl
    namespace: backend
    status: Synced
    version: v1
  - kind: ConfigMap
    name: backend-config
    namespace: backend
    status: Synced
    version: v1
  - health:
      status: Progressing
    kind: Service
    name: backen-svc
    namespace: backend
    status: Synced
    version: v1
```
Every look fine but I made an error in the configuration of the service, the LoadBalancer cannot assign an IP address.
Everything is sync

But health is still and will stay in progressing status 

Is there a way we can trigger when progressing is too long ?
