### ISSUE TITLE
Is there a better way to kustomize config.yaml

### ISSUE THREAD

**Issue by hasueki** [argoproj-labs/argocd-notifications#76]
Hi there,

I am using kustomize to generate the manifests needed to install argocd-notifications, and wanted to ask if there is a better way to "kustomize" the `config.yaml` value in `argocd-notifications-cm` ConfigMap. 

I have created a kustomize base that just pulls in the manifests from https://github.com/argoproj-labs/argocd-notifications/tree/master/manifests/controller, and then adds custom templates and enabled triggers via a patch merge of the ConfigMap. This variant will become the "base" for all of my `argocd-notifications` installations.

Then for each installation, I want to create another overlay that just sets the appropriate `context` in `config.yaml` (e.g. argocdUrl and clusterName). Using kustomize with multiple overlay layers, it becomes difficult to set a value if that value is inside a multiline string.

I am working around by setting the `context`, `templates`, `triggers` in each overlay, but not ideal because in my use case, `templates` and `triggers` are not changing per overlay and leads to duplication of configs in multiple places.

Couple possible solutions that I can think of:
- Ability for templates/templating to access environment variables attached to the main controller. 
- Add support for separating out `config.yaml` into it's own respective yamls (e.g. context.yaml, templates.yaml, triggers.yaml, etc)

I didn't see anything in the source that will allow me to achieve such setup, unless I missed something.

**Comment by alexmt** [comment]
Hello @hasueki,

I agree with the issue. I really like your second proposal. Instead of using `config.yaml`, `notifiers.yaml` we could use separate config map keys. For example

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  trigger.my-custom-trigger: |
        condition: app.status.sync.status == 'Unknown'
        template: my-custom-template
  template.my-custom-template: |
        title: Hello {{.app.metadata.name}}
        body: |
          Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
```
instead of:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: my-custom-trigger
        condition: app.status.sync.status == 'Unknown'
        template: my-custom-template
    templates:
      # Add your custom template
      - name: my-custom-template
        title: Hello {{.app.metadata.name}}
        body: |
          Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
```

This would simplify kustomize usage and also enable proposal described in https://github.com/argoproj-labs/argocd-notifications/issues/56
