### ISSUE TITLE
Failed to parse settings

### ISSUE THREAD

**Issue by yagince** [argoproj-labs/argocd-notifications#80]
Image: argoprojlabs/argocd-notifications:v0.6.1

I created the following ConfigMap and Secret.
It fails to parse Secret at startup.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: on-sync-succeeded
        enabled: true
      - name: on-sync-running
        enabled: true
      - name: on-sync-failed
        enabled: true
      - name: on-health-degrated
        enabled: true
      - name: app-sync-status-unknown
        enabled: true
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      token: xoxb-xxxx
type: Opaque
```

Error message.
```
time="2020-05-01T10:56:36Z" level=fatal msg="Failed to parse new settings: syntax error: mismatched input '<EOF>' expecting {'len', 'all', 'none', 'any', 'one', 'filter', 'map', '[', '(', '{', '.', '+', '-', '!', 'not', 'nil', '#', BooleanLiteral, IntegerLiteral, FloatLiteral, HexIntegerLiteral, Identifier, StringLiteral} (1:1)"
```

I'm at a loss as to where I'm going wrong.
I would like some advice.

**Comment by alexmt** [comment]
Hello @yagince ,

I've implemented enhanced settings parsing error messages and added CLI [commands](https://argoproj-labs.github.io/argocd-notifications/troubleshooting/) that helps troubleshooting configuration issues.

Validated your configuration using the CLI tool and got following errors:

```
argocd-notifications tools template get --config-map /tmp/test.yaml --secret :empty

failed to parse config: trigger 'on-health-degrated' condition is empty
failed to parse config: trigger 'app-sync-status-unknown' condition is empty
```

Looks like two triggers has an incorrect name. Please try to change config map as following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: on-sync-succeeded
        enabled: true
      - name: on-sync-running
        enabled: true
      - name: on-sync-failed
        enabled: true
      - name: on-health-degraded# instead of on-health-degrated
        enabled: true
      - name: on-sync-status-unknown #instead of app-sync-status-unknown
        enabled: true
```
