### ISSUE TITLE
is there any way to disable the email login?

### ISSUE THREAD

**Issue by keanlee** [argoproj-labs/argocd-notifications#96]
Since our internal Email server can not need a login, is there any way we can disable the email login?

**Comment by alex1989hu** [comment]
Hello @keanlee, this works for me with: `v0.7.0`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
stringData:
  notifiers.yaml: |
    email:
      host: mail.foo.bar
      port: 25
      username: ""
      password: ""
      from: no-reply-foo@bar.com
```
